Repository KAU-projectX/projectX-BE, pull requests merged in 2024-04, with the labels that each got.

#1 feat: CD 스크립트 생성
  .github/workflows/deploy.yml
Labels: 🛠feature

#4 feat: sample 확인을 위한 controller 생성
  src/main/java/com/projectX/projectX/docker/controller/DockerRestController.java
Labels: 🛠feature

#6 feat: docker compose.yml 생성
  docker-compose.yml
Labels: 🛠feature

#9 feat: docker-compose main 적용
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  build.gradle
  docker-compose.yml
  gradle.properties
  src/main/java/com/projectX/projectX/docker/controller/DockerRestController.java
Labels: 🛠feature

#10 feat: docker-compose.yml 추가 수정
  docker-compose.yml
Labels: bug

#20 Feat/#19 create entity
  build.gradle
  src/main/java/com/projectX/projectX/domain/member/entity/Member.java
  src/main/java/com/projectX/projectX/domain/tour/entity/Sido.java
  src/main/java/com/projectX/projectX/domain/tour/entity/Sigungu.java
  src/main/java/com/projectX/projectX/domain/tour/entity/Tour.java
  src/main/java/com/projectX/projectX/domain/tour/entity/TourImage.java
  src/main/java/com/projectX/projectX/domain/tour/entity/TourImpairment.java
  src/main/java/com/projectX/projectX/global/common/BaseEntity.java
  src/main/java/com/projectX/projectX/global/common/ContentType.java
  src/main/java/com/projectX/projectX/global/common/ResponseDTO.java
  src/main/resources/application.yml
Labels: 🛠feature

#22 Docker Sample Controller 삭제
  src/main/java/com/projectX/projectX/docker/controller/DockerRestController.java
Labels: 🛠 fix

#25 Global Exception Handler 적용
  src/main/java/com/projectX/projectX/global/exception/ApplicationException.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
  src/main/java/com/projectX/projectX/global/exception/ForbiddenException.java
  src/main/java/com/projectX/projectX/global/exception/GlobalExceptionHandler.java
  src/main/java/com/projectX/projectX/global/exception/InternalServerException.java
Labels: ✏feature

#28 Feat/#27 create swagger
  build.gradle
  src/main/java/com/projectX/projectX/global/config/SwaggerConfig.java
Labels: ✏feature

#30 기본 회원가입 로직 구현
  build.gradle
  src/main/java/com/projectX/projectX/domain/member/controller/MemberRestController.java
  src/main/java/com/projectX/projectX/domain/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/projectX/projectX/domain/member/dto/response/MemberSignUpResponse.java
  src/main/java/com/projectX/projectX/domain/member/entity/Authority.java
  src/main/java/com/projectX/projectX/domain/member/exception/AlreadyExistIdException.java
  src/main/java/com/projectX/projectX/domain/member/exception/InvalidPasswordException.java
  src/main/java/com/projectX/projectX/domain/member/repository/MemberRepository.java
  src/main/java/com/projectX/projectX/domain/member/service/MemberService.java
  src/main/java/com/projectX/projectX/domain/member/util/MemberMapper.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
Labels: ✏feature

#34 delete: MemberSignUp 제거
  src/main/java/com/projectX/projectX/domain/member/controller/MemberRestController.java
  src/main/java/com/projectX/projectX/domain/member/service/MemberService.java
Labels: 🐞 bug

#35 feat: Member entity 변경
  build.gradle
  src/main/java/com/projectX/projectX/domain/member/entity/Authority.java
  src/main/java/com/projectX/projectX/domain/member/entity/Member.java
  src/main/java/com/projectX/projectX/domain/member/entity/ProviderType.java
  src/main/java/com/projectX/projectX/domain/member/entity/RoleType.java
  src/main/java/com/projectX/projectX/domain/member/util/MemberMapper.java
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: ✏feature, 🛠 fix

#36 feat: memberRepository 변경
  src/main/java/com/projectX/projectX/domain/member/repository/MemberRepository.java
Labels: 🐞 bug, ✏feature

#39 feat: TourImage TourImpairment entity 변경
  src/main/java/com/projectX/projectX/domain/tour/entity/TourImage.java
  src/main/java/com/projectX/projectX/domain/tour/entity/TourImpairment.java
Labels: ✏feature

#38 Feat/#26 create inquiry of area code
  build.gradle
  src/main/java/com/projectX/projectX/domain/tour/controller/TourRestController.java
  src/main/java/com/projectX/projectX/domain/tour/dto/request/TourSidoStoreRequest.java
  src/main/java/com/projectX/projectX/domain/tour/dto/request/TourSigunguStoreRequest.java
  src/main/java/com/projectX/projectX/domain/tour/dto/response/TourSidoStoreResponse.java
  src/main/java/com/projectX/projectX/domain/tour/entity/Sido.java
  src/main/java/com/projectX/projectX/domain/tour/entity/Sigungu.java
  src/main/java/com/projectX/projectX/domain/tour/exception/InvalidAreaCodeException.java
  src/main/java/com/projectX/projectX/domain/tour/repository/SidoRepository.java
  src/main/java/com/projectX/projectX/domain/tour/repository/SigunguRepository.java
  src/main/java/com/projectX/projectX/domain/tour/service/TourService.java
  src/main/java/com/projectX/projectX/domain/tour/util/TourMapper.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: ✏feature

#44 Feat/#37 create barrier free data
  src/main/java/com/projectX/projectX/domain/tour/controller/TourRestController.java
  src/main/java/com/projectX/projectX/domain/tour/dto/request/TourImpairmentRequest.java
  src/main/java/com/projectX/projectX/domain/tour/entity/TourImpairment.java
  src/main/java/com/projectX/projectX/domain/tour/exception/ContentIdNotFoundException.java
  src/main/java/com/projectX/projectX/domain/tour/exception/InvalidRequestException.java
  src/main/java/com/projectX/projectX/domain/tour/exception/InvalidURIException.java
  src/main/java/com/projectX/projectX/domain/tour/repository/ImpairmentRepository.java
  src/main/java/com/projectX/projectX/domain/tour/repository/SidoRepository.java
  src/main/java/com/projectX/projectX/domain/tour/repository/TourRepository.java
  src/main/java/com/projectX/projectX/domain/tour/service/TourService.java
  src/main/java/com/projectX/projectX/domain/tour/util/TourMapper.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: 🩹refactor, ✏feature, 🛠 fix

#45 Feat/#41 create barrier free image data
  src/main/java/com/projectX/projectX/domain/tour/controller/TourRestController.java
  src/main/java/com/projectX/projectX/domain/tour/entity/TourImage.java
  src/main/java/com/projectX/projectX/domain/tour/repository/TourImageRepository.java
  src/main/java/com/projectX/projectX/domain/tour/service/TourService.java
  src/main/java/com/projectX/projectX/domain/tour/util/TourMapper.java
Labels: 🩹refactor, ✏feature, 🛠 fix

#46 Feat/#43 create common info data
  src/main/java/com/projectX/projectX/domain/tour/controller/TourRestController.java
  src/main/java/com/projectX/projectX/domain/tour/entity/Tour.java
  src/main/java/com/projectX/projectX/domain/tour/service/TourService.java
Labels: ✏feature
