Repository KAU-projectX/projectX-BE, pull requests merged in 2024-06, with the labels that each got.

#59 Refactor/#54 refactor cafe domain
  src/main/java/com/projectX/projectX/domain/cafe/controller/CafeRestController.java
  src/main/java/com/projectX/projectX/domain/cafe/entity/Cafe.java
  src/main/java/com/projectX/projectX/domain/cafe/repository/CafeBulkRepository.java
  src/main/java/com/projectX/projectX/domain/cafe/repository/CafeRepository.java
  src/main/java/com/projectX/projectX/domain/cafe/service/CSVReader.java
  src/main/java/com/projectX/projectX/domain/cafe/service/CafeService.java
  src/main/java/com/projectX/projectX/domain/cafe/service/LibraryService.java
  src/main/java/com/projectX/projectX/domain/cafe/util/CSVReader.java
  src/main/java/com/projectX/projectX/domain/cafe/util/CafeMapper.java
  src/main/java/com/projectX/projectX/domain/cafe/util/HttpUtil.java
  src/main/java/com/projectX/projectX/domain/cafe/util/JsonUtil.java
Labels: 🩹refactor

#60 Feat/#56 create log out
  src/main/java/com/projectX/projectX/domain/member/controller/MemberRestController.java
  src/main/java/com/projectX/projectX/domain/member/exception/InvalidTokenException.java
  src/main/java/com/projectX/projectX/domain/member/repository/MemberAuthRepository.java
  src/main/java/com/projectX/projectX/domain/member/service/MemberService.java
  src/main/java/com/projectX/projectX/global/security/util/JwtUtil.java
Labels: ✏feature

#62 Feat/#52 check cafe exist reversion
  build.gradle
  src/main/java/com/projectX/projectX/domain/cafe/entity/Cafe.java
  src/main/java/com/projectX/projectX/domain/cafe/repository/CafeBulkRepository.java
  src/main/java/com/projectX/projectX/domain/cafe/service/CafeService.java
  src/main/java/com/projectX/projectX/global/security/filter/JwtAuthFilter.java
  src/main/java/com/projectX/projectX/global/security/filter/JwtExceptionFilter.java
  src/main/resources/application-local.yml
Labels: ✏feature

#68 Feat/#66 add jeju region on cafe
  src/main/java/com/projectX/projectX/domain/cafe/entity/Cafe.java
  src/main/java/com/projectX/projectX/domain/cafe/repository/CafeBulkRepository.java
  src/main/java/com/projectX/projectX/domain/cafe/service/CafeService.java
  src/main/java/com/projectX/projectX/domain/tour/service/TourService.java
  src/main/java/com/projectX/projectX/global/common/CommonService.java
Labels: ✏feature, 🛠 fix

#71 Bugfix/#69 fix security login
  src/main/java/com/projectX/projectX/domain/member/entity/Member.java
  src/main/java/com/projectX/projectX/domain/member/entity/ProviderType.java
  src/main/java/com/projectX/projectX/domain/member/exception/InvalidProviderTypeException.java
  src/main/java/com/projectX/projectX/domain/member/util/MemberMapper.java
  src/main/java/com/projectX/projectX/global/config/SecurityConfig.java
  src/main/java/com/projectX/projectX/global/config/SwaggerConfig.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
  src/main/java/com/projectX/projectX/global/security/dto/CustomOAuth2User.java
  src/main/java/com/projectX/projectX/global/security/dto/SecurityUser.java
  src/main/java/com/projectX/projectX/global/security/filter/JwtAuthFilter.java
  src/main/java/com/projectX/projectX/global/security/filter/JwtExceptionFilter.java
  src/main/java/com/projectX/projectX/global/security/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/projectX/projectX/global/security/service/OAuthAttribute.java
  src/main/java/com/projectX/projectX/global/security/service/OAuthService.java
  src/main/java/com/projectX/projectX/global/security/util/JwtUtil.java
  src/main/resources/application-local.yml
Labels: ✏feature, 🛠 fix

#70 Feat/#63 create work all
  src/main/java/com/projectX/projectX/domain/cafe/repository/CafeRepository.java
  src/main/java/com/projectX/projectX/domain/work/controller/WorkRestController.java
  src/main/java/com/projectX/projectX/domain/work/dto/response/WorkGetAllResponse.java
  src/main/java/com/projectX/projectX/domain/work/exception/InvalidPageException.java
  src/main/java/com/projectX/projectX/domain/work/exception/NoMorePageException.java
  src/main/java/com/projectX/projectX/domain/work/exception/WorkNotFoundException.java
  src/main/java/com/projectX/projectX/domain/work/service/WorkService.java
  src/main/java/com/projectX/projectX/domain/work/util/WorkUtil.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
Labels: ✏feature

#75 fix: Docker compose를 활용한 CD 스크립트로 변경
  .github/workflows/deploy.yml
Labels: 🐞 bug, ✏feature, 🛠 fix

#73 feat: docker compose에 redis 추가
  elasticbeanstalk/docker-compose.yml
Labels: 🐞 bug, ✏feature

#76 feat: 토큰 재발급 api 구현
  src/main/java/com/projectX/projectX/domain/member/controller/MemberAuthRestController.java
  src/main/java/com/projectX/projectX/domain/member/service/MemberAuthService.java
Labels: ✏feature

#78 feat: 로그아웃 swagger comment 추가
  src/main/java/com/projectX/projectX/domain/member/controller/MemberRestController.java
Labels: 📝 documentation

#80 Feat/#79 create get all travels
  src/main/java/com/projectX/projectX/domain/tour/repository/TourRepository.java
  src/main/java/com/projectX/projectX/domain/travel/controller/TravelRestController.java
  src/main/java/com/projectX/projectX/domain/travel/dto/response/TravelGetAllResponse.java
  src/main/java/com/projectX/projectX/domain/travel/exception/TravelNotFoundException.java
  src/main/java/com/projectX/projectX/domain/travel/service/TravelService.java
  src/main/java/com/projectX/projectX/domain/travel/util/TravelMapper.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
Labels: ✏feature

#84 Feat/#81 create specific tour info
  src/main/java/com/projectX/projectX/domain/travel/controller/TravelRestController.java
  src/main/java/com/projectX/projectX/domain/travel/dto/response/TravelGetSpecificResponse.java
  src/main/java/com/projectX/projectX/domain/travel/service/TravelService.java
  src/main/java/com/projectX/projectX/domain/travel/util/TravelMapper.java
Labels: ✏feature

#85 feat: work 상세 정보 조회
  src/main/java/com/projectX/projectX/domain/work/controller/WorkRestController.java
  src/main/java/com/projectX/projectX/domain/work/dto/response/WorkGetDetailResponse.java
  src/main/java/com/projectX/projectX/domain/work/service/WorkService.java
  src/main/java/com/projectX/projectX/domain/work/util/WorkMapper.java
  src/main/java/com/projectX/projectX/domain/work/util/WorkUtil.java
Labels: ✏feature

#87 add: addJejuRegionOnLibrary
  src/main/java/com/projectX/projectX/domain/cafe/service/LibraryService.java
Labels: 🛠 fix

#89 Bugfix/#88 fix db error
  src/main/java/com/projectX/projectX/domain/tour/service/TourService.java
Labels: 🐞 bug

#90 fix: 서버 파일 형식에 맞춰 띄어쓰기 제거
  src/main/java/com/projectX/projectX/domain/cafe/service/CafeService.java
Labels: 🐞 bug

#91 fix: 서버 파일 형식에 맞춰 영어로 변경
  src/main/java/com/projectX/projectX/domain/cafe/service/CafeService.java
Labels: 🐞 bug

#93 fix: container에 csv 넣는 코드 추가
  .github/workflows/deploy.yml
Labels: 🐞 bug, 🛠 fix

#95 fix: 힙 메모리 추가 할당
  elasticbeanstalk/docker-compose.yml
Labels: 🐞 bug, 🛠 fix

#97 feat: work 정보에 image 추가
  src/main/java/com/projectX/projectX/domain/work/dto/response/WorkGetAllResponse.java
  src/main/java/com/projectX/projectX/domain/work/dto/response/WorkGetDetailResponse.java
  src/main/java/com/projectX/projectX/domain/work/util/WorkMapper.java
Labels: ✏feature
