Repository KAU-projectX/projectX-BE, pull requests merged in 2024-09, with the labels that each got.

#118 [FEAT] work 리뷰 조회 및 수정 api 생성
  src/main/java/com/projectX/projectX/domain/review/controller/CafeReviewRestController.java
  src/main/java/com/projectX/projectX/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/projectX/projectX/domain/review/dto/response/ReviewGetAllResponse.java
  src/main/java/com/projectX/projectX/domain/review/entity/CafeReview.java
  src/main/java/com/projectX/projectX/domain/review/repository/CafeReviewRepository.java
  src/main/java/com/projectX/projectX/domain/review/service/CafeReviewService.java
  src/main/java/com/projectX/projectX/domain/review/util/CafeReviewMapper.java
  src/main/java/com/projectX/projectX/domain/review/util/ReviewMapper.java
  src/main/java/com/projectX/projectX/global/common/RecommendationType.java
  src/main/java/com/projectX/projectX/global/exception/ExceptionHandler.java
Labels: ✏feature

#122 [BUG] work 단일/전체조회에서의 에러 해결
  src/main/java/com/projectX/projectX/domain/work/controller/WorkRestController.java
  src/main/java/com/projectX/projectX/domain/work/service/WorkService.java
Labels: 🐞 bug

#127 [REFACTOR] 리뷰 도메인 리팩토링
  src/main/java/com/projectX/projectX/domain/review/controller/CafeReviewRestController.java
  src/main/java/com/projectX/projectX/domain/review/controller/TourReviewRestController.java
  src/main/java/com/projectX/projectX/domain/review/dto/response/ReviewGetAllResponse.java
  src/main/java/com/projectX/projectX/domain/review/entity/CafeReview.java
  src/main/java/com/projectX/projectX/domain/review/entity/RecommendationType.java
  src/main/java/com/projectX/projectX/domain/review/entity/TourReview.java
  src/main/java/com/projectX/projectX/domain/review/repository/CafeReviewRepository.java
  src/main/java/com/projectX/projectX/domain/review/service/CafeReviewService.java
  src/main/java/com/projectX/projectX/domain/review/service/TourReviewService.java
  src/main/java/com/projectX/projectX/domain/review/util/CafeReviewMapper.java
  src/main/java/com/projectX/projectX/domain/review/util/TourReviewMapper.java
  src/main/java/com/projectX/projectX/domain/work/controller/WorkRestController.java
Labels: 🩹refactor

#123 Feat/#119 create calendar
  src/main/java/com/projectX/projectX/domain/calendar/controller/CalendarRestController.java
  src/main/java/com/projectX/projectX/domain/calendar/dto/request/CalendarScheduleRequest.java
  src/main/java/com/projectX/projectX/domain/calendar/entity/Calendar.java
  src/main/java/com/projectX/projectX/domain/calendar/entity/ScheduleType.java
  src/main/java/com/projectX/projectX/domain/calendar/exception/InvalidScheduleTypeException.java
  src/main/java/com/projectX/projectX/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/projectX/projectX/domain/calendar/service/CalendarService.java
  src/main/java/com/projectX/projectX/domain/calendar/util/CalendarMapper.java
  src/main/java/com/projectX/projectX/global/exception/ErrorCode.java
Labels: ✏feature

#128 Feat/#124 get calendar
  src/main/java/com/projectX/projectX/domain/calendar/controller/CalendarRestController.java
  src/main/java/com/projectX/projectX/domain/calendar/dto/response/AllCalendarScheduleResponse.java
  src/main/java/com/projectX/projectX/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/projectX/projectX/domain/calendar/service/CalendarService.java
Labels: ✏feature
